# Uncomment this line to define a global platform for your project
platform :ios, '9.0'
# Uncomment this line if you're using Swift
use_frameworks!

def sharedPods
    pod 'Alamofire', '~> 4.0'
    pod 'Freddy'
    pod 'Valet', :git => 'https://github.com/square/Valet.git', :branch => 'develop/3.0'
    pod 'MBProgressHUD', '~> 0.9.1'
    pod 'AFDateHelper', '~> 3.5'
    pod 'SnapKit', '~> 3.0'
    pod 'syncano-ios'  
    pod 'JSQMessagesViewController'
end

target ‘PeoplemonSKC’ do
    sharedPods
end
